apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: lschulzes/auth
      context: .
      docker:
        dockerfile: services/auth/Dockerfile.dev
      sync:
        manual:
          - src: "services/**/*.ts"
            dest: .
          - src: "services/**/*.tsx"
            dest: .
    - image: lschulzes/client
      context: .
      docker:
        dockerfile: services/client/Dockerfile.dev
      sync:
        manual:
          - src: "services/**/*.ts"
            dest: .
          - src: "services/**/*.tsx"
            dest: .
    - image: lschulzes/tickets
      context: .
      docker:
        dockerfile: services/tickets/Dockerfile.dev
      sync:
        manual:
          - src: "services/**/*.ts"
            dest: .
          - src: "services/**/*.tsx"
            dest: .
