apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: lschulzes/auth
      context: .
      docker:
        dockerfile: services/auth/Dockerfile
      sync:
        manual:
          - src: "packages/**/*.ts"
            dest: .
          - src: "services/**/*.ts"
            dest: .
          - src: "services/**/*.tsx"
            dest: .
    - image: lschulzes/client
      context: .
      docker:
        dockerfile: services/client/Dockerfile
      sync:
        manual:
          - src: "packages/**/*.ts"
            dest: .
          - src: "services/**/*.ts"
            dest: .
          - src: "services/**/*.tsx"
            dest: .
    - image: lschulzes/tickets
      context: .
      docker:
        dockerfile: services/tickets/Dockerfile
      sync:
        manual:
          - src: "packages/**/*.ts"
            dest: .
          - src: "services/**/*.ts"
            dest: .
          - src: "services/**/*.tsx"
            dest: .
    - image: lschulzes/orders
      context: .
      docker:
        dockerfile: services/orders/Dockerfile
      sync:
        manual:
          - src: "packages/**/*.ts"
            dest: .
          - src: "services/**/*.ts"
            dest: .
          - src: "services/**/*.tsx"
            dest: .
    - image: lschulzes/expiration
      context: .
      docker:
        dockerfile: services/expiration/Dockerfile
      sync:
        manual:
          - src: "packages/**/*.ts"
            dest: .
          - src: "services/**/*.ts"
            dest: .
          - src: "services/**/*.tsx"
            dest: .
    - image: lschulzes/payments
      context: .
      docker:
        dockerfile: services/payments/Dockerfile
      sync:
        manual:
          - src: "packages/**/*.ts"
            dest: .
          - src: "services/**/*.ts"
            dest: .
          - src: "services/**/*.tsx"
            dest: .
