name: tests-payments

on:
  pull_request:
    paths:
      - "services/payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services/payments && yarn && yarn test:ci
