name: tests-orders

on:
  pull_request:
    paths:
      - "services/orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services/orders && yarn && yarn test:ci
